// src/components/react/Counter.tsx
import { useState } from "react";

interface Props {
  message: string;
}

export function Counter({ message }: Props) {
  const [count, setCount] = useState(0);

  return (
    <div>
      <div i-tabler:brand-react bg-blue-500 px-4 py-2 />
      <p>{message}</p>
      <button type="button" onClick={() => setCount(count + 1)}>
        Count: {count}
      </button>
    </div>
  );
}

// src/components/vue/Counter.vue
<script setup lang="ts">
import { ref } from 'vue';

interface Props {
  message: string;
}

defineProps<Props>();

const count = ref(0);

function increment() {
  count.value++;
}
</script>

<template>
  <div>
    <div i-tabler:brand-vue rounded bg-green-500 px-4 py-2 />
    <p>{{ message }}</p>
    <button type="button" @click="increment">
      Count: {{ count }}
    </button>
  </div>
</template>
